class PrivacyPage < SitePrism::Page
  set_url '/privacy'

  element :heading, '.heading-xlarge'
  element :overview, 'a[href="#overview"]'
  element :overview_text, '#overview', text: "Overview The Scottish Qualification Authority (SQA) is administering the multiplication tables check (MTC) technical pre-test trials on behalf of the Standards and Testing Agency (STA). The trials will take place in a sample of schools from 25 June to 6 July 2018. STA will use the results of the trial to: create a range of check forms (online question papers) to ensure they are of comparable difficulty for implementing in national checks from 2020 develop and refine the digital service for implementing live checks STA is the data controller for the trials and is responsible for determining how personal data collected during the period will be treated. As with all trials of new national assessments, we will not publish the results of the check, and no individual school or pupil will be identified. As data processor, SQA is responsible for securely storing and handling any personal data required to administer the trials. They will securely dispose of this data at the end of the MTC contract, in accordance with the agreement with STA, and in line with the requirements of UK data protection legislation and the General Data Protection Regulation (GDPR) ."
  element :data_collected_and_who_can_access, 'a[href="#data-collection-and-access"]'
  element :data_collected_and_who_can_access_text, '#data-collection-and-access', text: "What data will be collected and who can access it? STA and SQA will collect and hold data they need to administer the trials: selected pupils’ names pupils’ dates of birth unique pupil numbers (UPNs) names of schools MTC trials are completed online by selected pupils. Their completed test results remain within the MTC system, to which only STA has access. Access within STA will be restricted to those employees who need to see the pupil data. SQA will share the pupil data with their test administrators. Test administrators will only see the data for pupils for those schools in which they are administering trials. After the trial, SQA will return any pupil data to STA, with the additional data they have collected. This will include test attendance register data, which will comprise school and pupils’ names, pupils’ dates of birth and UPNs. This data will be used to match collected pupil data to the pupil concerned and to confirm which pupils from the sample have taken the tests. All data for the trial will be supplied in electronic data files and sent by secure file transfer protocol. No information gathered during the trial will be transferred or stored outside of the EEA. SQA handles personal data in accordance with the rights given to individuals under UK data protection legislation. Data subjects have a right to see information held about them and SQA will cooperate fully when a subject access request is made of the data controller (in this instance, STA)."
  element :retaining_personal_data, 'a[href="#retaining-personal-data"]'
  element :retaining_personal_data_text, '#retaining-personal-data', text: "Retaining personal data Data collected by SQA will be retained for up to 6 months following the end of the trial, as agreed by STA and SQA. On STA’s approval, SQA will destroy data and permanently delete computer files from their systems. Any paper copies of check materials returned to SQA will be shredded securely on site. STA will only keep personal data for as long as it is needed for the purpose(s) of this project, after which point it will be securely destroyed. Please note that, under section 33 of the Data Protection Act 1998, and in compliance with the relevant conditions, we can lawfully keep personal data processed purely for research purposes indefinitely."
  element :further_information, 'a[href="#further-information"]'
  element :further_information_text, '#further-information', text: "Further information If you have any queries about MTC trial data, please email mtc@sqa.org.uk. STA, as an executive agency of the Department for Education (DfE), determines the purposes and means of processing personal data as part of this project. You can find more information in the DfE’s personal information charter . You have the right to lodge a complaint about data protection issues with the Information Commissioner’s Office. More information is available on their website."
  element :gdpr_link, 'a[href="https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr"]'
  element :email_sqa, 'a[href="mailto:mtc@sqa.org.uk"]'
  element :personal_information_charter_link, 'a[href="https://www.gov.uk/government/organisations/department-for-education/about/personal-information-charter"]'
  element :ico_link, 'a[href="https://ico.org.uk/make-a-complaint"]'
  element :back_to_top, 'a[href="#top"]'

end